name: mytorch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - scikit-learn=0.22.1=py37hd81dba3_0
  - pandas=1.0.3=py37h0573a6f_0
  - pip:
    - gensim==3.8.3
